paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  outputs: "outputs"
  models: "models"

features:
  drop_col: ["AN_EXERC", 'CHARGE', 'DEROG14']
  id_col: "ID"
  target_freq: "FREQ"
  target_cm: 'CM'

training:
  model_name: "xgboost"
  random_state: 42
  cv_folds: 5            
  save_model: true

preprocessing:
  numerical:
    imputer: "median"  
    scaler: "robust"   
  categorical:
    imputer: "most_frequent"
    encoding: "onehot"

# Default parameters (overwritten by best_params.yaml if it exists)
model_params:
  xgboost_freq:
    objective: "count:poisson"
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 4
  xgboost_cm:
    objective: "reg:gamma"  # ou reg:tweedie avec tweedie_variance_power=1.5
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 4
  lightgbm:
    n_estimators: 100
    learning_rate: 0.1
  ridge:
    alpha: 1.0